@hostaddress = https://localhost:7059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZGY4OWExNi1mNTdkLTRmMDItYjViYi00MjIzMmRmZjExYjkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJpbmZvQG1lZGlhbi5kayIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzY2NDE5OTY3LCJpc3MiOiJtZWRpYW4uYXV0aCIsImF1ZCI6Im1lZGlhbi53ZWJhcHAifQ.2JHO4k4I6Q6akRI-INT0fqXLjDigk3QeZOUFt6f_t2w

GET {{hostaddress}}/weatherforecast/
Accept: application/json

### login

POST {{hostaddress}}/login
Content-Type: application/json

{
  "email": "info@median.dk",
  "password": "test1234"
}

### get profile
GET {{hostaddress}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZGY4OWExNi1mNTdkLTRmMDItYjViYi00MjIzMmRmZjExYjkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJpbmZvQG1lZGlhbi5kayIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzY2NDE5OTY3LCJpc3MiOiJtZWRpYW4uYXV0aCIsImF1ZCI6Im1lZGlhbi53ZWJhcHAifQ.2JHO4k4I6Q6akRI-INT0fqXLjDigk3QeZOUFt6f_t2w


### Test get weatherforecast
GET {{hostaddress}}/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZGY4OWExNi1mNTdkLTRmMDItYjViYi00MjIzMmRmZjExYjkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJpbmZvQG1lZGlhbi5kayIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzY2NDE5OTY3LCJpc3MiOiJtZWRpYW4uYXV0aCIsImF1ZCI6Im1lZGlhbi53ZWJhcHAifQ.2JHO4k4I6Q6akRI-INT0fqXLjDigk3QeZOUFt6f_t2w
